[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
lazy_static = { version = "1.5.0", optional = true }
ralph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"], optional = true }
tracing = { version = "0.1", optional = true }

[features]
server = ["dioxus/server", "ralph/server", "tokio", "lazy_static", "tracing"]
tokio = ["dep:tokio"]
lazy_static = ["dep:lazy_static"]
tracing = ["dep:tracing"]
