[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
api = { workspace = true }
ralph = { workspace = true }
web-sys = { version = "0.3", features = ["Window", "Storage"], optional = true }

[features]
server = ["api/server"]
web = ["web-sys"]
